name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r min_ratio_cycle/
      
      - name: Run Safety check
        run: |
          pip install safety
          safety check
      
      - name: Dependency vulnerability scan
        uses: pypa/gh-action-pip-audit@v1.0.8
